### ISSUE TITLE
使用RAG做知识问答时，lambda报错。

### ISSUE THREAD

**Issue by heqiqi** [aws-samples/private-llm-qa-bot#204]
**Ask_Assistant** lambda 的cloudwatch log：
![image](https://github.com/aws-samples/private-llm-qa-bot/assets/3094813/92c00999-b1a5-4a36-8fa6-edf87f86871f)

chatbot界面错误：
![image](https://github.com/aws-samples/private-llm-qa-bot/assets/3094813/0a27f10f-2a02-4b90-8264-9bc773916e12)

**Comment by heqiqi** [comment]
main.py里判断是否default
`
##如果指定了prompt 模板
    if template_id and template_id != 'default':
        prompt_template = get_template(template_id)
        prompt_template = 'default' if prompt_template is None else prompt_template['template']['S']
`
frontend前端，使用value是：prompt_template_id : 1698905450793-bcfab8 

root cause

**Comment by ybalbert001** [comment]
fixed by v1.1.5
