### ISSUE TITLE
知识库创建Script Dimension 设置

### ISSUE THREAD

**Issue by brilliantwf** [aws-samples/private-llm-qa-bot#206]
# OpenSearch的endpoint，可以从上面的Cloudformation的output中获取
# Dimension 是向量模型的输出维度，由选择的模型确定
sh setup_knowledgebase.sh ${OpensearchEndpoint} ${Dimension}

这里{Dimension} 具体要设置为多少?模型和{Dimension}的关系是怎样?

**Comment by ybalbert001** [comment]
模型有个输出维度，向量库需要与之对齐，一般以768，1024， 1536居多，sentence transformer里面模型，多数为768， bge，cohere模型是1024， openai和titan的是1536。
